export const logCategories = [
  { value: '전체' },
  { value: '프론트엔드' },
  { value: '백엔드' },
  { value: '데이터분석' },
  { value: '서버개발' },
  { value: 'DBA' },
  { value: 'IOS 개발' },
  { value: '안드로이드 개발' },
  { value: 'React' },
  { value: 'Typescript' },
  { value: 'Next' },
  { value: 'Pocketbae' },
  { value: 'Firebase' },
];
